#############################################################################
# This config file is a necessary input file for the cactus GPU snakemake
# pipeline. It contains the parameters needed to run the pipeline.
#############################################################################

# time -p snakemake -p -s cactus_gpu.smk --configfile tests/evolverMammals-cfg.yaml --profile profiles/slurm_profile/ --dryrun

#############################################################################
#
# Below are the parameters you need to set for the cactus snakemake pipeline.
#

cactus_path: 
# File path or "download".
# Provide the path to the cactus singularity container. 
# If you don't have it, set this to "download" and the pipeline will download it for you.

input_file: 
# File path.
# Same as input file for cactus-prepare, though a similar file with ancestor genomes should have been created in your output directory
# when you ran cactus-prepare.

output_dir: 
# Directory path.
# The desired output directory for the snakemake pipeline. This directory will be created if it doesn't exist.

overwrite_output_dir:
# True/False.
# If the output directory already exists and you don't care if the files within it might be overwritten, set this to True.
# Otherwise, set it to False and the pipeline will exit and tell you if the output directory already exists.

final_hal: 
# File path.
# The name you want for the final HAL file. This will be created within output_dir.

tmp_dir:
# Directory path.
# A temporary directory for snakemake and cactus to use. Should have lots of space.

use_gpu:
# True/False.
# Whether or not to use the GPU version of cactus.
# If you have GPU partitions and want to use them, set this to True.
# If you don't have a GPU partition, set this to False.

#############################################################################
## Below are the partitions and resources for each rule in the snakemake pipeline.
## Be sure to adjust them to meet your needs and the resources available on your cluster.
## Notably, for mask, blast, and align, if you use the GPU version of cactus, you will need to
## provide a partition with GPUs and set the gpu values to the number of GPUs you want to use.
## If you are not using the cactus GPU version, the gpu values will be ignored.
##
## The partitions are specific to the Harvard cluster. If you run this on a different cluster
## you must change them.

mask_partition: ""  # If use_gpu is True, this must be a partition with GPUs
mask_gpu:           # If use_gpu is False, this will be ignored
mask_cpu: 
mask_mem:           # in MB
mask_time:          # in minutes

##########################

blast_partition: "" # If use_gpu is True, this must be a partition with GPUs
blast_gpu:          # If use_gpu is False, this will be ignored -- CURRENTLY ONLY WORKS WITH 1 GPU
blast_cpu: 
blast_mem:          # in MB
blast_time:         # in minutes

##########################

align_partition: "" # If use_gpu is True, this must be a partition with GPUs
align_gpu:          # If use_gpu is False, this will be ignored
align_cpu: 
align_mem:          # in MB
align_time:         # in minutes

##########################

convert_partition: ""
convert_cpu: 
convert_mem:        # in MB
convert_time:       # in minutes

##########################

copy_partition: ""
copy_cpu: 
copy_mem:           # in MB
copy_time:          # in minutes

##########################

append_partition: ""
append_cpu: 
append_mem:         # in MB
append_time:        # in minutes

##########################

maf_partition: ""
maf_cpu: 
maf_mem:            # in MB
maf_time:           # in minutes

##########################