#############################################################################
# This config file is a necessary input file for the Cactus add outgroup Snakemake
# pipeline: cactus_add_outgroup.smk. It contains the parameters needed to run the pipeline.
#############################################################################

# time -p snakemake -j 5 -e slurm -s cactus_add_outgroup.smk --configfile config-templates/add-outgroup-config-template.yaml --dryrun

#############################################################################
#
# Below are the parameters you need to set for the cactus snakemake pipeline.
# YOU WILL NEED TO CHANGE THESE
#

cactus_path:
# File path or version string (e.g. 2.9.5) or "download".
# Provide the path to the cactus singularity container. This is needed whether use_gpu is True or False.
# If you don't have it, set this to "download" and the pipeline will download it for you.
# If you want to download a specific version, provide the version tag, e.g. v2.9.9

input_hal:
# File path.
# The input HAL file. This is the output of a previous cactus run.

old_root_name:
# String.
# The name of the root node in the input HAL file.

new_genome_name:
# String
# The name of the new genome to be added to the HAL file as an outgroup.
# This will also be the name in the tree.

new_genome_fasta:
# File path.
# The path to the genome file to be added to the HAL file.

new_root_name:
# String.
# The name of the new root node that will be created in the tree.

branch_length_from_new_genome:
# Float or blank (defaults to 1.0).
# The branch length of the new branch connecting the new genome to new_root_name.

branch_length_from_old_root:
# Float or blank (defaults to 1.0).
# The branch length of the new branch connecting the old_root_name to new_root_name.

output_dir:
# Directory path.
# The output directory for the snakemake pipeline. This should be the same as the outDir in cactus-prepare.
# This directory will be created if it doesn't exist.

final_prefix:
# String.
# The prefix for the final output files. This will be used to name the final HAL file and the final MAF files.

maf_reference:
# String.
# The reference genome for the MAF files. This should be the name of the reference genome in the input_file.

tmp_dir:
# Directory path.
# A temporary directory for snakemake and cactus to use. Should have lots of space.

use_gpu:
# True/False.
# Whether or not to use the GPU version of cactus.
# If you don't have a GPU partition, set this to False.
# Either way, be sure to set the correct values for the partitions and GPUs below.

#############################################################################
## Below are the partitions and resources for each rule in the snakemake pipeline.
## Be sure to adjust them to meet your needs and the resources available on your cluster.
## Notably, for rule blast, if you use the GPU version of cactus you will need to
## provide a partition with GPUs and set gpus to the number of GPUs you want to use.
## If you are not using the cactus GPU version, the gpus value will be ignored.
##
## The partitions are specific to the Harvard cluster. If you run this on a different cluster
## you must change them.
##
## mem_mb is in MB
## time is in minutes
##
## If using the snakemake-executor-plugin-cannon (-e cannon), partition names can be left blank.

rule_resources:
  default:
    partition: 
    mem_mb: 
    cpus: 
    time:   

  get_root_fasta:
    partition: 
    mem_mb: 
    cpus: 
    time: 

  preprocess:
    partition: 
    mem_mb: 
    cpus: 
    time: 

  blast:
    partition:  # If use_gpu is True, this must be a partition with GPUs
    mem_mb: 
    cpus: 
    gpus:            # If use_gpu is False, this will be ignored
    time: 

  align:
    partition: 
    mem_mb: 
    cpus: 
    time: 

  combine_hals:
    partition: 
    mem_mb: 
    cpus: 
    time: 

  maf:
    partition: 
    mem_mb: 
    cpus: 
    time: 
